name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 69.62.75.29 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@69.62.75.29 << 'EOF'
            cd bonbaan-BE/

            # Optional: pull latest changes if repo is already cloned
            git pull origin main

            # Optional: stop old containers
            docker compose down

            # Run your Docker Compose
            docker compose up -d --build
          EOF
