name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 69.62.75.29 >> ~/.ssh/known_hosts

      - name: Deploy via SSH and Docker Compose
        run: |
            ssh -tt -i github-actions-key ubuntu@69.62.75.29 << 'EOF'
                cd /bonbaan-BE/
                git pull origin main
                docker compose down
                docker compose up -d --build
                EOF
