name: Go-test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Copy .env.test file
        run: cp .env.test .env

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
